edition = "2021"
tab_spaces = 2
max_width = 80
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Module"
format_strings = true
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
