on: [pull_request, push]

name: check

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1.0.7
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: check
